version: '3.9'

services:
  estudos-api:
    env_file: .env
    container_name: ${CONTAINER_NAME}
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: "America/Fortaleza"
    ports:
      - ${SERVER_PORT_EXTERNAL}:8080
    restart: always


  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: ${POSTGRESQL_NAME}
    hostname: ${POSTGRESQL_HOST}
    ports:
      - ${POSTGRESQL_PORT_EXTERNAL}:5432
    volumes:
      - ${POSTGRESQL_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "America/Fortaleza"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3